version: "3"

services:
  postgres:
    build:
      context: ./docker/postgres
    container_name: "${DOCKER_CONTAINER_PREFIX}-postgres"
    restart: "always"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  node:
    container_name: "${DOCKER_CONTAINER_PREFIX}-node"
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    command: nodemon server.js
    ports:
      - "${PORT}:3333"
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: "always"
    volumes:
      - .:/home/linex/backend
    links:
      - postgres

  adminer:
    build:
      context: ./docker/adminer
    container_name: "linex-adminer"
    restart: "always"
    ports:
      - "8080:8080"
    links:
      - postgres
